welcome:
  message: Welcome To The HomePage!!!!

spring:
  application:
    name: SpringBoot
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: abubakkerabu
  jpa:
    hibernate:
      ddl-auto: update
    show: true